### ISSUE TITLE
Backward compatibility in PyQt6

### ISSUE THREAD

**Issue by Herizoran** [mottosso/Qt.py#465]
There is a method where I use `QtCore.Qt.DisplayRole`
It raises an error in PyQt6 but works very well in PyQt5.
Error:
`AttributeError: type object 'Qt' has no attribute 'DisplayRole'
`

**Comment by MHendricks** [comment]
Yeah, PyQt6 requires using the fully qualified enum values. This goes over it and shows the cli tool to find and update uses in code. https://github.com/mottosso/Qt.py/blob/master/CAVEATS.md#fully-qualified-enums

The change for DisplayRole is `QtCore.Qt.DisplayRole` to `QtCore.Qt.ItemDataRole.DisplayRole`.

PySide6 still provides backwards compatibility but I think they were hinting that they also want to remove these eventually, they may have even had a flag for it.

**Comment by Herizoran** [comment]
@MHendricks thank you for clarifying.
yes, I noticed PyQt6 using enums for some objects...
But that does mean, this Qt.py doesn't convert the older method to make it compatible in PyQt6?

**Comment by MHendricks** [comment]
You can already natively use the fully qualified enums in Qt5(at least in 5.15 and I believe it works in 5.12). The [Qt_convert_enum](https://github.com/mottosso/Qt.py/blob/master/src/Qt_convert_enum.py) tool provides a easy way to update your code and we use it as a qc check in our CI to ensure that we don't have any regressions.

Also if you need to convert enums to ints, you should use `QtCompat.enumValue` which handles the differences between Qt5 and 6. You can re-cast the value to the enum constructor so you can deal with strict type checks.

```py
as_int = Qt.QtCompat.enumValue(Qt.QtCore.Qt.ItemDataRole.DisplayRole)
as_enum = Qt.QtCore.Qt.ItemDataRole(as_int)
```

<br>
<br>

I don't think it's possible(practical) to have Qt provide compatibility wrappers for all Qt enums. `Qt.QtCore.Qt` are the original PyQt/PySide objects not Qt.py wrappers. 
```py
>>> Qt.QtCore
<module 'Qt.QtCore'>
>>> Qt.QtCore.Qt
<class 'PyQt5.QtCore.Qt'>
>>> Qt.QtCore.QObject
<class 'PyQt5.QtCore.QObject'>
```
So we would have to create wrappers around every possible Qt enum, Using `Qt_convert_enum.py" --show map` shows me 22,825 enums, that does include some duplication from sub-classes, but we would have to map and expose all of those.

The simpler approach is to just make sure you always use fully qualified enums as long as you are only using Qt5/6.

**Comment by Herizoran** [comment]
Okay! That's a great explanation!
Thank you so much!
